# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=255)),
                ('links', models.ManyToManyField(to='chatbot.Message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Response'),
        ),
    ]
