# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='response',
            name='links',
            field=models.ManyToManyField(blank=True, to='chatbot.Message'),
        ),
    ]
