# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20160918_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='partial_match',
            field=models.BooleanField(default=False),
        ),
    ]
