# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 09:00
from __future__ import unicode_literals

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_message_partial_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chatbot.models.get_image_path),
        ),
    ]
