# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20160918_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ManyToManyField(blank=True, to='chatbot.Response')),
            ],
        ),
    ]
