# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_responsequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsequeue',
            name='title',
            field=models.CharField(default='Default', max_length=255),
        ),
    ]
