# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_responsequeue_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_queue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.ResponseQueue')),
            ],
        ),
    ]
