# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 10:28
from __future__ import unicode_literals

import chatbot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=chatbot.models.get_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='active_bot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Bot'),
            preserve_default=False,
        ),
    ]
